# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a5d755fc42245f2b04e8c560d38d94bb1c9937aba289bc6f60edc28b5e34ac43fbd0e96866703b51185cb9a63c333f80812a4b3ccaf0aa7a8a8ff63abe8a7e

test:
  secret_key_base: 33e0a2133702ef9427910e3e5659c8fe2d690cc8046330bb5d19c7eec766d869287307a2bf3a6ed444bf7e944769aab6779c44689a8bc9001660f70c0c372d9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
